#+TITLE: lamia.org --- My personal GNU Emacs configuration
#+AUTHOR: Geoffrey T. Wark


* First Things First

Save backups and auto-saves to the system's =temp= directory.

#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist
	`((".*" . ,temporary-file-directory)))
  (setq auto-save-file-name-transforms
	`((".*" ,temporary-file-directory t)))
#+END_SRC

Move customization information to its own file.  This avoids cluttering [[file:init.el][init.el]].

#+BEGIN_SRC emacs-lisp
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (load custom-file t)
#+END_SRC

Ask for confirmation when leaving Emacs.

#+BEGIN_SRC emacs-lisp
  (setq confirm-kill-emacs 'yes-or-no-p)
#+END_SRC

* UI
** Theme

#+BEGIN_SRC emacs-lisp
  (use-package zenburn-theme
    :ensure t
    :config
    (load-theme 'zenburn t))
#+END_SRC

Make cursor more obvious and stop the goddamn blinking!

#+BEGIN_SRC emacs-lisp
  (set-cursor-color "red")
  (blink-cursor-mode 0)
#+END_SRC

** Font

[[https://sourcefoundry.org/hack/][Hack]] is a nice, easy-to-read font.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'default-frame-alist '(font . "Hack-11"))
#+END_SRC

** General

Free up screen real estate.

#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
#+END_SRC

* Indentation

Indent with spaces instead of tabs.

#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
#+END_SRC

* Packages

Ensure packages get installed if not already present on the machine.

#+BEGIN_SRC emacs-lisp
  (require 'use-package-ensure)
  (setq use-package-always-ensure t)
#+END_SRC

Keep packages up-to-date.

#+BEGIN_SRC emacs-lisp
  (use-package auto-package-update
    :config
    (setq auto-package-update-delete-old-versions t)
    (setq auto-package-update-hide-results t)
    (auto-package-update-maybe))
#+END_SRC

** From MELPA
*** magit

A Git porcelain inside Emacs.

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :bind ("C-c g" . magit)
    :config
    (setq magit-display-buffer-function #'magit-display-buffer-fullframe-status-v1))
#+END_SRC

*** smex

M-x interface with Ido-style fuzzy matching.

#+BEGIN_SRC emacs-lisp
  (use-package smex
    :bind (("M-x" . smex)
           ("M-X" . smex-major-mode-commands))
    :init
    (smex-initialize))
#+END_SRC

** Built-in
*** Ido

Interactively Do Things

#+BEGIN_SRC emacs-lisp
  (ido-mode t)
#+END_SRC

** Org mode related

Per [[https://orgmode.org/worg/org-tutorials/orgtutorial_dto.html][David O'Toole's Org tutorial]].

#+BEGIN_SRC emacs-lisp
  (require 'org)
  (define-key global-map "\C-ca" #'org-agenda)
  (setq org-log-done 'time)
#+END_SRC


* Finishing Touches
** Load Private Settings

For settings that are me specific.

#+BEGIN_SRC emacs-lisp
  (load "~/Nextcloud/docs/private.el" t)
#+END_SRC
